owner: einsteintoolkit
repo: uptime

sites:
  - name: EinsteinToolkit website
    url: https://www.einsteintoolkit.org
  - name: CactusCode website
    url: https://www.cactuscode.org
  - name: EinsteinToolkit wiki
    url: https://docs.einsteintoolkit.org
    icon: https://www.wikipedia.org/static/favicon/wikipedia.ico
  - name: Tutorial server
    url: https://etk.cct.lsu.edu
    icon: https://jupyter.org/favicon.ico
    # LSU's "InCommon RSA Server CA" is not recognized (by curl or wget, or upptime, but is by browsers)
    __dangerous__disable_verify_peer: true
  - name: Cactus SVN server
    # LSUs server does not use modern TLS and GitHub may refuse to talk to it
    url: http://svn.cactuscode.org
    icon: https://subversion.apache.org/icon.png
  - name: EinsteinToolkit SVN server
    # LSUs server does not use modern TLS and GitHub may refuse to talk to it
    url: http://svn.einsteintoolkit.org
    icon: https://subversion.apache.org/icon.png
  - name: EinsteinToolkit mailing list server
    url: https://lists.einsteintoolkit.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://www.einsteintoolkit.org/images/logo/einstein_right.svg
  name: Einstein Toolkit status
  introTitle: "Einstein Toolkit relativistic astrophysics toolkit."
  introMessage: The [Einstein Toolkit](https://www.einsteintoolkit.org) is a [community-driven](http://einsteintoolkit.org/members.html) software platform of core computational tools to advance and support research in relativistic astrophysics and gravitational physics.
  navbar:
    - title: Status
      href: /uptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Contact
      href: mailto:maintainers@einsteintoolkit.org

workflowSchedule:
  graphs: "0 12 * * *"
  responseTime: "29 8 * * *"
  staticSite: "1 4 * * *"
  summary: "54 10 * * *"
  updateTemplate: "5 17 * * *"
  updates: "36 10 * * *"
  uptime: "*/15 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
